In [ ]:
import pandas as pd 
import json
import glob
from datetime import datetime

In [ ]:
round= "3"
directory_list = ["data"+round+"/*.csv"]

text_files = list(map(lambda x: glob.glob(x), directory_list))
text_files = [item for sublist in text_files for item in sublist]
# print(text_files)
twt_data = [] 
twt_csv = []
for csv_file in text_files:
  q = pd.read_csv(csv_file)
  # print(csv_file)
  for index, row in q.iterrows():
    creatd_at = row['created_at'] 
    timestamp = datetime.strptime(creatd_at,'%Y-%m-%d %H:%M:%S').date()
    # print(type(timestamp))
    twt_data.append((row['author'],row['statusId'],row['text'],row['retweetCount'],row['favoriteCount'],timestamp))

twt_csv = pd.DataFrame(twt_data,columns=['author','status_Id','text','retweetCount','favoriteCount','timestamp'])
twt_csv.to_csv("travel_content"+round+".csv")

In [ ]:
twt_csv.head(100)

          author            status_Id  ... favoriteCount   timestamp
0   NerdECrafter  1348469052323336192  ...             1  2021-01-11
1   NerdECrafter  1348448577635418112  ...             1  2021-01-11
2   NerdECrafter  1348444444568264704  ...             1  2021-01-11
3   NerdECrafter  1348444391862661121  ...             1  2021-01-11
4   NerdECrafter  1348443760842125327  ...             2  2021-01-11
..           ...                  ...  ...           ...         ...
95  NerdECrafter  1343358037520752640  ...             1  2020-12-28
96  NerdECrafter  1343357981514199040  ...             1  2020-12-28
97  NerdECrafter  1343357801431785479  ...             1  2020-12-28
98  NerdECrafter  1343326161884086274  ...             7  2020-12-27
99  NerdECrafter  1343322334824984577  ...           106  2020-12-27

[100 rows x 6 columns]